AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Zemnme:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/backend
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
